# Jekyll
permalink: /:year-:month-:day/:title/
paginate: 5
name: Blake Butcher
gems: [jekyll-paginate]
baseurl: /
production_url : http://blakebutcher.com
navigation:
- text: Blog
  url: /
  section: blog
- text: Follow
  url: /follow/
  section: follow
- text: CV
  url: /cv/
  section: cv
author :
  name : Blake Butcher
  email : blake.butcher+via-blakebutcher.com@gmail.com
  github : blakebutcher
  twitter : blakebutcher
